In [8]:
import numpy as np

In [9]:
a = np.array([
    [1, 2, 3],
    [6, 7, 8]
])
a

array([[1, 2, 3],
       [6, 7, 8]])

In [12]:
print(a[0])
print(a[0, 1])

[1 2 3]
2


In [14]:
a = np.arange(5)
a + 20
a

array([0, 1, 2, 3, 4])